### ISSUE TITLE
小细节：侧滑返回手势问题

### ISSUE THREAD

**Issue by chenzhengxu** [mrriddler/MicroKernel#2]
微应用第一个页面开始侧滑返回手势即会调用popViewController导致微应用deinit释放，如果此时取消侧滑手势，则会发生该页面对应微应用已释放而页面栈未释放该页面的情况

**Comment by mrriddler** [comment]
这个是MicroKernelNavigationController回调时机问题，有时间我修一下

**Comment by mrriddler** [comment]
已修复

> 微应用第一个页面开始侧滑返回手势即会调用popViewController导致微应用deinit释放，如果此时取消侧滑手势，则会发生该页面对应微应用已释放而页面栈未释放该页面的情况
