### ISSUE TITLE
能出个OC版的吗？

### ISSUE THREAD

**Issue by CircularCyanStone** [mrriddler/MicroKernel#3]

**Comment by mrriddler** [comment]
swift直接桥接使用吧...

**Comment by littlepriest** [comment]
我以前很抗拒斯威夫特，觉得就那样吧。
直到后来写了一次。
简直停不下来。
以前听人说，用了斯威夫特就回不去了，或者很难。
现在想想。确实是哦。思维和习惯都变了。好玩的东西真多。
